spring.datasource.url=jdbc:postgresql://localhost:50000/sourcery
spring.datasource.username=student
spring.datasource.password=sourcery
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:50000/sourcery
spring.flyway.user=student
spring.flyway.password=sourcery
spring.flyway.locations=classpath:db/migration/postgres

spring.jpa.show-sql=true
security.jwt.token.secret=cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
security.jwt.token.validity=60m
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true